import dotenv from 'dotenv';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import mongoose from 'mongoose';
import Product from '../src/models/Product';

// Load environment variables from .env.local
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
dotenv.config({ path: join(__dirname, '..', '.env.local') });

/**
 * Seed script to insert all 37 products into MongoDB
 *
 * Usage: npx tsx scripts/seed-products.ts
 */

const productsData = [
  {
    name: "Premium Chia Seeds",
    slug: "premium-chia-seeds",
    description: "100% Natural Raw Chia Seeds - High in Protein & Fiber. Perfect for smoothies, yogurt, and healthy recipes. Dairy-free and vegan-friendly superfood packed with omega-3 fatty acids.",
    shortDescription: "Premium Chia Seeds, 100% Natural Raw, High in Fiber",
    price: 250,
    originalPrice: 400,
    category: "Superfoods",
    subcategory: "Seeds",
    sku: "TAPTI-CHIA-001",
    stock: 50,
    weight: 200,
    weightUnit: "g",
    isFeatured: true,
    isActive: true,
    images: [{ url: "https://images.meesho.com/images/products/610646788/wuofi_512.webp", publicId: "tapti-chia-001-0", order: 0 }],
    tags: ["chia seeds", "superfood", "healthy", "vegan", "protein"],
    averageRating: 4.5,
    totalReviews: 23,
  },
  {
    name: "Natural Jaggery Combo Pack",
    slug: "natural-jaggery-combo",
    description: "Pure Natural Jaggery Combo - 500g Cubes + 500g Powder. Chemical-free traditional sweetener, rich in iron and minerals. Perfect replacement for refined sugar in all your recipes.",
    shortDescription: "Natural Jaggery Combo | 500g Cubes + 500g Powder",
    price: 313,
    originalPrice: 450,
    category: "Sweeteners",
    subcategory: "Jaggery",
    sku: "TAPTI-JAG-COMBO-001",
    stock: 40,
    weight: 1000,
    weightUnit: "g",
    isFeatured: true,
    isActive: true,
    images: [{ url: "https://images.meesho.com/images/products/603502006/ppnkj_512.webp", publicId: "tapti-jag-combo-001-0", order: 0 }],
    tags: ["jaggery", "natural sweetener", "organic", "healthy"],
    averageRating: 4.7,
    totalReviews: 45,
  },
  {
    name: "Pure Jaggery Cubes",
    slug: "pure-jaggery-cubes",
    description: "Pure Jaggery Cubes 500g - Natural Gud, Chemical Free. Traditional Indian sweetener made from sugarcane juice. Rich in iron, magnesium, and potassium for better health.",
    shortDescription: "Pure Jaggery Cubes 500g, Natural Gud, Chemical Free",
    price: 273,
    originalPrice: 350,
    category: "Sweeteners",
    subcategory: "Jaggery",
    sku: "TAPTI-JAG-CUBE-001",
    stock: 60,
    weight: 500,
    weightUnit: "g",
    isFeatured: false,
    isActive: true,
    images: [{ url: "https://images.meesho.com/images/products/603463542/syhgj_512.webp", publicId: "tapti-jag-cube-001-0", order: 0 }],
    tags: ["jaggery", "cubes", "natural", "healthy"],
    averageRating: 4.6,
    totalReviews: 31,
  },
  {
    name: "Premium Rajma (Kidney Beans)",
    slug: "premium-rajma-kidney-beans",
    description: "Premium Dudh Mogra Speckled Rajma - Protein Rich Kidney Beans. Naturally unpolished, high-quality pulses perfect for authentic North Indian recipes. Excellent source of plant-based protein.",
    shortDescription: "Premium Dudh Mogra Speckled Rajma, Protein Rich",
    price: 430,
    originalPrice: 550,
    category: "Pulses & Grains",
    subcategory: "Beans",
    sku: "TAPTI-RAJMA-001",
    stock: 35,
    weight: 1000,
    weightUnit: "g",
    isFeatured: true,
    isActive: true,
    images: [{ url: "https://images.meesho.com/images/products/580624828/ot9ue_512.webp", publicId: "tapti-rajma-001-0", order: 0 }],
    tags: ["rajma", "kidney beans", "pulses", "protein", "dal"],
    averageRating: 4.8,
    totalReviews: 52,
  },
  {
    name: "Mixed Dry Fruits Powder",
    slug: "mixed-dry-fruits-powder",
    description: "Natural Dry Fruit Powder - Rich in Protein & Vitamins. Blend of premium dry fruits including almonds, cashews, and pistachios. Perfect for milk, smoothies, and desserts.",
    shortDescription: "Natural Dry Fruit Powder, Rich in Protein & Vitamins",
    price: 351,
    originalPrice: 500,
    category: "Dry Fruits",
    subcategory: "Powder",
    sku: "TAPTI-DRY-MIX-001",
    stock: 25,
    weight: 250,
    weightUnit: "g",
    isFeatured: true,
    isActive: true,
    images: [{ url: "https://images.meesho.com/images/products/610662805/0hh8f_512.webp", publicId: "tapti-dry-mix-001-0", order: 0 }],
    tags: ["dry fruits", "powder", "healthy", "vitamins", "nutrition"],
    averageRating: 4.4,
    totalReviews: 18,
  },
  {
    name: "Premium Kashmiri Saffron",
    slug: "premium-kashmiri-saffron",
    description: "Premium Kashmiri Saffron - 100% Pure Natural Kesar. Authentic saffron threads for cooking, desserts, and traditional ceremonies. Known for its rich aroma and deep color.",
    shortDescription: "Premium Kashmiri Saffron, 100% Pure Natural Kesar",
    price: 192,
    originalPrice: 250,
    category: "Spices",
    subcategory: "Saffron",
    sku: "TAPTI-SAFF-001",
    stock: 20,
    weight: 1,
    weightUnit: "g",
    isFeatured: true,
    isActive: true,
    images: [{ url: "https://images.meesho.com/images/products/612121311/khjw1_512.webp", publicId: "tapti-saff-001-0", order: 0 }],
    tags: ["saffron", "kesar", "premium", "kashmiri", "spice"],
    averageRating: 4.9,
    totalReviews: 67,
  },
  {
    name: "Mix Dry Fruits Powder Premium",
    slug: "mix-dry-fruits-powder-premium",
    description: "Nutrimix Naturals Premium Dry Fruit Mixture - Mix of finest nuts and dried fruits. Energy-boosting blend rich in healthy fats, protein, and antioxidants.",
    shortDescription: "Nutrimix Naturals Premium Dry Fruit Mixture",
    price: 331,
    originalPrice: 450,
    category: "Dry Fruits",
    subcategory: "Powder",
    sku: "TAPTI-DRY-PREM-001",
    stock: 30,
    weight: 200,
    weightUnit: "g",
    isFeatured: false,
    isActive: true,
    images: [{ url: "https://images.meesho.com/images/products/581277662/bynx5_512.webp", publicId: "tapti-dry-prem-001-0", order: 0 }],
    tags: ["dry fruits", "premium", "nutrition", "healthy"],
    averageRating: 4.5,
    totalReviews: 22,
  },
  {
    name: "Crispy Kurodi Papad",
    slug: "crispy-kurodi-papad",
    description: "Crispy Kurodi - Taste of Maharashtra Papad. Authentic traditional papad made with quality ingredients. Perfect accompaniment for Indian meals.",
    shortDescription: "Crispy Kurodi Taste of Maharashtra Papad",
    price: 190,
    originalPrice: 250,
    category: "Snacks",
    subcategory: "Papad",
    sku: "TAPTI-PAPAD-001",
    stock: 45,
    weight: 200,
    weightUnit: "g",
    isFeatured: false,
    isActive: true,
    images: [{ url: "https://images.meesho.com/images/products/565715264/dus29_512.webp", publicId: "tapti-papad-001-0", order: 0 }],
    tags: ["papad", "snacks", "crispy", "traditional"],
    averageRating: 4.3,
    totalReviews: 15,
  },
  {
    name: "Organic Chia Seeds 500g",
    slug: "organic-chia-seeds-500g",
    description: "Premium Raw Chia Seeds 500g - High Protein & Fiber. Sugar-free, vegan superfood perfect for weight management and heart health. Rich in omega-3 and antioxidants.",
    shortDescription: "Premium Raw Chia Seeds 500g, High Protein & Fiber",
    price: 280,
    originalPrice: 400,
    category: "Superfoods",
    subcategory: "Seeds",
    sku: "TAPTI-CHIA-500-001",
    stock: 40,
    weight: 500,
    weightUnit: "g",
    isFeatured: false,
    isActive: true,
    images: [{ url: "https://images.meesho.com/images/products/604759385/sca9q_512.webp", publicId: "tapti-chia-500-001-0", order: 0 }],
    tags: ["chia seeds", "organic", "superfood", "protein"],
    averageRating: 4.6,
    totalReviews: 28,
  },
  {
    name: "Pure Jaggery Cubes 150g",
    slug: "pure-jaggery-cubes-150g",
    description: "Pure Jaggery Cubes 150g - Natural Gud, Chemical Free. Small pack perfect for trying. Traditional sweetener rich in minerals and iron.",
    shortDescription: "Pure Jaggery Cubes 150g, Natural Gud, Chemical Free",
    price: 178,
    originalPrice: 220,
    category: "Sweeteners",
    subcategory: "Jaggery",
    sku: "TAPTI-JAG-150-001",
    stock: 55,
    weight: 150,
    weightUnit: "g",
    isFeatured: false,
    isActive: true,
    images: [{ url: "https://images.meesho.com/images/products/603484448/oguiy_512.webp", publicId: "tapti-jag-150-001-0", order: 0 }],
    tags: ["jaggery", "small pack", "natural"],
    averageRating: 4.5,
    totalReviews: 19,
  },
  {
    name: "Royal Kashmiri Saffron 5gm",
    slug: "royal-kashmiri-saffron-5gm",
    description: "Royal Kashmiri Kesar 5gm Threads - Premium quality for cooking & puja. Authentic saffron with certification. Intense aroma and color.",
    shortDescription: "Royal Kashmiri Kesar 5gm Threads for Cooking & Puja",
    price: 1018,
    originalPrice: 1500,
    category: "Spices",
    subcategory: "Saffron",
    sku: "TAPTI-SAFF-ROYAL-001",
    stock: 10,
    weight: 5,
    weightUnit: "g",
    isFeatured: true,
    isActive: true,
    images: [{ url: "https://images.meesho.com/images/products/612629980/reh7o_512.webp", publicId: "tapti-saff-royal-001-0", order: 0 }],
    tags: ["saffron", "royal", "premium", "kashmiri"],
    averageRating: 5.0,
    totalReviews: 42,
  },
  {
    name: "Natural Gond Katira",
    slug: "natural-gond-katira",
    description: "Natural Gond Katira - Rich in Fiber for Skin & Hair. Ayurvedic superfood with cooling properties. Excellent for summer drinks and beauty care.",
    shortDescription: "Natural Gond Katira, Rich in Fiber for Skin & Hair",
    price: 196,
    originalPrice: 280,
    category: "Ayurvedic",
    subcategory: "Herbs",
    sku: "TAPTI-GOND-001",
    stock: 30,
    weight: 100,
    weightUnit: "g",
    isFeatured: false,
    isActive: true,
    images: [{ url: "https://images.meesho.com/images/products/621542930/qwdzn_512.webp", publicId: "tapti-gond-001-0", order: 0 }],
    tags: ["gond katira", "ayurvedic", "natural", "health"],
    averageRating: 4.4,
    totalReviews: 14,
  },
  {
    name: "Chemical Free Jaggery Powder",
    slug: "chemical-free-jaggery-powder",
    description: "Chemical Free Jaggery Powder - Pure Desi Gud, Healthy. Fine powder form for easy mixing in recipes. Natural sweetener with health benefits.",
    shortDescription: "Chemical Free Jaggery Powder, Pure Des Gud, Healthy",
    price: 133,
    originalPrice: 180,
    category: "Sweeteners",
    subcategory: "Jaggery",
    sku: "TAPTI-JAG-POW-001",
    stock: 50,
    weight: 250,
    weightUnit: "g",
    isFeatured: false,
    isActive: true,
    images: [{ url: "https://images.meesho.com/images/products/572068187/kbdkk_512.webp", publicId: "tapti-jag-pow-001-0", order: 0 }],
    tags: ["jaggery", "powder", "chemical free", "healthy"],
    averageRating: 4.5,
    totalReviews: 21,
  },
  {
    name: "Pure Tulsi Powder",
    slug: "pure-tulsi-powder",
    description: "Pure Tulsi Powder - Holy Basil Leaf Powder 100g. Ayurvedic herb known for immunity boosting. Rich in antioxidants and adaptogens.",
    shortDescription: "Pure Tulsi Powder, Holy Basil Leaf Powder, 100g",
    price: 159,
    originalPrice: 200,
    category: "Ayurvedic",
    subcategory: "Herbs",
    sku: "TAPTI-TULSI-001",
    stock: 35,
    weight: 100,
    weightUnit: "g",
    isFeatured: false,
    isActive: true,
    images: [{ url: "https://images.meesho.com/images/products/572102536/kshyd_512.webp", publicId: "tapti-tulsi-001-0", order: 0 }],
    tags: ["tulsi", "ayurvedic", "immunity", "herbal"],
    averageRating: 4.7,
    totalReviews: 33,
  },
  {
    name: "Neem Tulsi Mix Powder",
    slug: "neem-tulsi-mix-powder",
    description: "Neem Tulsi Mix Powder - 100% Natural Herbal Blend. Powerful combination for skin care and immunity. Detoxifying and purifying properties.",
    shortDescription: "Neem Tulsi Mix Powder, 100% Natural Herbal Blend",
    price: 132,
    originalPrice: 180,
    category: "Ayurvedic",
    subcategory: "Herbs",
    sku: "TAPTI-NEEM-TULSI-001",
    stock: 40,
    weight: 100,
    weightUnit: "g",
    isFeatured: false,
    isActive: true,
    images: [{ url: "https://images.meesho.com/images/products/572085452/cwxnk_512.webp", publicId: "tapti-neem-tulsi-001-0", order: 0 }],
    tags: ["neem", "tulsi", "ayurvedic", "skincare"],
    averageRating: 4.6,
    totalReviews: 27,
  },
  {
    name: "Organic Moringa Powder",
    slug: "organic-moringa-powder",
    description: "Organic Moringa Powder - Sahjan Patti Powder, Herbal. Nutrient-dense superfood rich in vitamins, minerals, and amino acids. Immunity booster.",
    shortDescription: "Organic Moringa Powder Sahjan Patti Powder, Herbal",
    price: 133,
    originalPrice: 180,
    category: "Ayurvedic",
    subcategory: "Superfoods",
    sku: "TAPTI-MORINGA-001",
    stock: 30,
    weight: 100,
    weightUnit: "g",
    isFeatured: false,
    isActive: true,
    images: [{ url: "https://images.meesho.com/images/products/581460345/dk5es_512.webp", publicId: "tapti-moringa-001-0", order: 0 }],
    tags: ["moringa", "organic", "superfood", "immunity"],
    averageRating: 4.5,
    totalReviews: 20,
  },
  {
    name: "Speckled Rajma Premium",
    slug: "speckled-rajma-premium",
    description: "Speckled Rajma - Natural Unpolished, Protein Rich. High-quality kidney beans perfect for traditional recipes. Excellent plant-based protein source.",
    shortDescription: "Speckled Rajma, Natural Unpolished, Protein Rich",
    price: 431,
    originalPrice: 550,
    category: "Pulses & Grains",
    subcategory: "Beans",
    sku: "TAPTI-RAJMA-PREM-001",
    stock: 40,
    weight: 1000,
    weightUnit: "g",
    isFeatured: false,
    isActive: true,
    images: [{ url: "https://images.meesho.com/images/products/580629150/l3xpe_512.webp", publicId: "tapti-rajma-prem-001-0", order: 0 }],
    tags: ["rajma", "pulses", "protein", "natural"],
    averageRating: 4.7,
    totalReviews: 38,
  },
  {
    name: "Premium Saffron Threads",
    slug: "premium-saffron-threads",
    description: "Premium Kashmiri Saffron Pure Kesar Threads - Natural. Authentic threads with rich color and aroma. Perfect for biryanis, desserts, and milk.",
    shortDescription: "Premium Kashmiri Saffron Pure Kesar Threads, Natural",
    price: 308,
    originalPrice: 450,
    category: "Spices",
    subcategory: "Saffron",
    sku: "TAPTI-SAFF-THREAD-001",
    stock: 25,
    weight: 2,
    weightUnit: "g",
    isFeatured: true,
    isActive: true,
    images: [{ url: "https://images.meesho.com/images/products/591372768/bjuqt_512.webp", publicId: "tapti-saff-thread-001-0", order: 0 }],
    tags: ["saffron", "threads", "kashmiri", "premium"],
    averageRating: 4.8,
    totalReviews: 51,
  },
  {
    name: "Organic Red Chilli Powder (Mirchi Powder)",
    slug: "organic-red-chilli-powder",
    description: "Organic Red Chilli Powder - Freshly ground from premium quality red chillies. Adds vibrant color and perfect heat to your dishes. 100% pure with no additives or artificial colors. Essential spice for Indian cooking.",
    shortDescription: "Organic Red Chilli Powder, Vibrant Color & Perfect Heat",
    price: 160,
    originalPrice: 200,
    category: "Spices & Masalas",
    subcategory: "Powders",
    sku: "TAPTI-MIRCHI-001",
    stock: 60,
    weight: 250,
    weightUnit: "g",
    isFeatured: false,
    isActive: true,
    images: [{ url: "/images/p17.jpg", publicId: "tapti-mirchi-001-0", order: 0 }],
    tags: ["mirchi", "red chilli", "chilli powder", "spice", "organic", "hot"],
    averageRating: 4.5,
    totalReviews: 0,
  },
  {
    name: "Organic Turmeric Powder (Haldi Powder)",
    slug: "organic-turmeric-powder",
    description: "Organic Turmeric Powder - Pure Haldi powder freshly ground from premium turmeric roots. Rich in curcumin with natural anti-inflammatory properties. Adds beautiful golden color and earthy flavor to your cooking. Essential for health and taste.",
    shortDescription: "Organic Turmeric Powder, Pure Haldi, Rich in Curcumin",
    price: 140,
    originalPrice: 180,
    category: "Spices & Masalas",
    subcategory: "Powders",
    sku: "TAPTI-HALDI-001",
    stock: 70,
    weight: 250,
    weightUnit: "g",
    isFeatured: true,
    isActive: true,
    images: [{ url: "/images/p9.jpg", publicId: "tapti-haldi-001-0", order: 0 }],
    tags: ["haldi", "turmeric", "curcumin", "organic", "spice", "health"],
    averageRating: 4.7,
    totalReviews: 0,
  },
  {
    name: "Organic Cumin Powder (Jeera Powder)",
    slug: "organic-cumin-powder",
    description: "Organic Cumin Powder - Freshly ground from premium quality cumin seeds. Aromatic and flavorful spice essential for tempering and seasoning. Rich in antioxidants and aids digestion. Perfect for curries, rice, and vegetables.",
    shortDescription: "Organic Cumin Powder, Aromatic & Flavorful",
    price: 150,
    originalPrice: 190,
    category: "Spices & Masalas",
    subcategory: "Powders",
    sku: "TAPTI-JEERA-001",
    stock: 65,
    weight: 250,
    weightUnit: "g",
    isFeatured: false,
    isActive: true,
    images: [{ url: "/images/p8.jpg", publicId: "tapti-jeera-001-0", order: 0 }],
    tags: ["cumin", "jeera", "spice", "organic", "aromatic", "digestion"],
    averageRating: 4.6,
    totalReviews: 0,
  },
  {
    name: "Organic Mustard Powder (Rai Powder)",
    slug: "organic-mustard-powder",
    description: "Organic Mustard Powder - Finely ground from quality mustard seeds. Adds pungent flavor and aroma to pickles, curries, and marinades. Rich in minerals and antioxidants. Essential for authentic Indian taste.",
    shortDescription: "Organic Mustard Powder, Pungent & Aromatic",
    price: 145,
    originalPrice: 185,
    category: "Spices & Masalas",
    subcategory: "Powders",
    sku: "TAPTI-RAI-POW-001",
    stock: 55,
    weight: 250,
    weightUnit: "g",
    isFeatured: false,
    isActive: true,
    images: [{ url: "/images/p5.jpg", publicId: "tapti-rai-pow-001-0", order: 0 }],
    tags: ["mustard", "rai", "spice", "organic", "pungent", "pickle"],
    averageRating: 4.5,
    totalReviews: 0,
  },
  {
    name: "Organic Coriander Powder (Dhania Powder)",
    slug: "organic-coriander-powder",
    description: "Organic Coriander Powder - Freshly ground from aromatic coriander seeds. Sweet, citrusy flavor that enhances curries, vegetables, and masala blends. Rich in fiber and antioxidants. Essential base spice for Indian cooking.",
    shortDescription: "Organic Coriander Powder, Sweet & Aromatic",
    price: 135,
    originalPrice: 175,
    category: "Spices & Masalas",
    subcategory: "Powders",
    sku: "TAPTI-DHANIA-001",
    stock: 75,
    weight: 250,
    weightUnit: "g",
    isFeatured: false,
    isActive: true,
    images: [{ url: "/images/p16.jpg", publicId: "tapti-dhania-001-0", order: 0 }],
    tags: ["coriander", "dhania", "spice", "organic", "aromatic", "curry"],
    averageRating: 4.6,
    totalReviews: 0,
  },
  {
    name: "Organic Garam Tadka Masala",
    slug: "organic-garam-tadka-masala",
    description: "Organic Garam Tadka Masala - Premium blend of roasted spices including cumin, mustard, and aromatic herbs. Perfect for tempering dals, curries, and vegetables. Adds instant flavor burst to your dishes. Freshly ground for maximum aroma.",
    shortDescription: "Organic Garam Tadka Masala, Premium Tempering Blend",
    price: 220,
    originalPrice: 280,
    category: "Spices & Masalas",
    subcategory: "Masala Blends",
    sku: "TAPTI-TADKA-001",
    stock: 50,
    weight: 250,
    weightUnit: "g",
    isFeatured: true,
    isActive: true,
    images: [{ url: "/images/p7.jpg", publicId: "tapti-tadka-001-0", order: 0 }],
    tags: ["garam masala", "tadka", "tempering", "spice blend", "organic", "aromatic"],
    averageRating: 4.8,
    totalReviews: 0,
  },
  {
    name: "Organic Garam Sabut Masala",
    slug: "organic-garam-sabut-masala",
    description: "Organic Garam Sabut Masala - Whole spice blend including black pepper, cardamom, cinnamon, bay leaves, and cloves. Traditional spice mix for authentic Indian curries and biryanis. Rich aroma and complex flavor. Premium quality whole spices.",
    shortDescription: "Organic Garam Sabut Masala, Whole Spice Blend",
    price: 240,
    originalPrice: 300,
    category: "Spices & Masalas",
    subcategory: "Masala Blends",
    sku: "TAPTI-SABUT-001",
    stock: 45,
    weight: 250,
    weightUnit: "g",
    isFeatured: false,
    isActive: true,
    images: [{ url: "/images/p6.jpg", publicId: "tapti-sabut-001-0", order: 0 }],
    tags: ["garam masala", "whole spices", "sabut masala", "organic", "biryani", "curry"],
    averageRating: 4.7,
    totalReviews: 0,
  },
  {
    name: "Organic Garlic Powder (Lahsun Powder)",
    slug: "organic-garlic-powder",
    description: "Organic Garlic Powder - Pure dehydrated garlic powder with intense flavor. Convenient alternative to fresh garlic for curries, soups, and marinades. Rich in allicin with health benefits. No additives, 100% natural.",
    shortDescription: "Organic Garlic Powder, Pure & Intense Flavor",
    price: 180,
    originalPrice: 230,
    category: "Specialty Powders",
    subcategory: "Vegetable Powders",
    sku: "TAPTI-GARLIC-001",
    stock: 50,
    weight: 250,
    weightUnit: "g",
    isFeatured: false,
    isActive: true,
    images: [{ url: "/images/p12.jpg", publicId: "tapti-garlic-001-0", order: 0 }],
    tags: ["garlic", "lahsun", "powder", "organic", "health", "flavor"],
    averageRating: 4.5,
    totalReviews: 0,
  },
  {
    name: "Organic White Onion Powder",
    slug: "organic-white-onion-powder",
    description: "Organic White Onion Powder - Pure dehydrated white onion powder with sweet, mild flavor. Perfect for soups, sauces, and dry rubs. Convenient alternative to fresh onions. Rich in quercetin and antioxidants. 100% natural with no additives.",
    shortDescription: "Organic White Onion Powder, Sweet & Mild",
    price: 170,
    originalPrice: 220,
    category: "Specialty Powders",
    subcategory: "Vegetable Powders",
    sku: "TAPTI-ONION-WHITE-001",
    stock: 55,
    weight: 250,
    weightUnit: "g",
    isFeatured: false,
    isActive: true,
    images: [{ url: "/images/p13.jpg", publicId: "tapti-onion-white-001-0", order: 0 }],
    tags: ["onion", "white onion", "powder", "organic", "flavor", "natural"],
    averageRating: 4.4,
    totalReviews: 0,
  },
  {
    name: "Organic Red Onion Powder",
    slug: "organic-red-onion-powder",
    description: "Organic Red Onion Powder - Pure dehydrated red onion powder with strong, pungent flavor. Ideal for curries, gravies, and spice blends. Rich in antioxidants and sulfur compounds. Convenient and long-lasting. 100% natural.",
    shortDescription: "Organic Red Onion Powder, Strong & Pungent",
    price: 175,
    originalPrice: 225,
    category: "Specialty Powders",
    subcategory: "Vegetable Powders",
    sku: "TAPTI-ONION-RED-001",
    stock: 50,
    weight: 250,
    weightUnit: "g",
    isFeatured: false,
    isActive: true,
    images: [{ url: "/images/p10.jpg", publicId: "tapti-onion-red-001-0", order: 0 }],
    tags: ["onion", "red onion", "powder", "organic", "pungent", "curry"],
    averageRating: 4.5,
    totalReviews: 0,
  },
  {
    name: "Organic Tomato Powder",
    slug: "organic-tomato-powder",
    description: "Organic Tomato Powder - Pure dehydrated tomato powder with rich, tangy flavor. Perfect for curries, soups, and pasta sauces. Rich in lycopene and vitamins. Instant flavor and color enhancement. No preservatives or additives.",
    shortDescription: "Organic Tomato Powder, Rich & Tangy",
    price: 190,
    originalPrice: 240,
    category: "Specialty Powders",
    subcategory: "Vegetable Powders",
    sku: "TAPTI-TOMATO-001",
    stock: 60,
    weight: 250,
    weightUnit: "g",
    isFeatured: false,
    isActive: true,
    images: [{ url: "/images/p15.jpg", publicId: "tapti-tomato-001-0", order: 0 }],
    tags: ["tomato", "powder", "organic", "tangy", "lycopene", "sauce"],
    averageRating: 4.6,
    totalReviews: 0,
  },
  {
    name: "Organic Ginger Powder (Adrak Powder)",
    slug: "organic-ginger-powder",
    description: "Organic Ginger Powder - Pure dried ginger powder with warm, spicy flavor. Excellent for tea, curries, and baking. Known for digestive and anti-inflammatory properties. Rich in gingerol. Premium quality, freshly ground.",
    shortDescription: "Organic Ginger Powder, Warm & Spicy",
    price: 165,
    originalPrice: 210,
    category: "Spices & Masalas",
    subcategory: "Powders",
    sku: "TAPTI-ADRAK-001",
    stock: 55,
    weight: 250,
    weightUnit: "g",
    isFeatured: false,
    isActive: true,
    images: [{ url: "/images/p11.jpg", publicId: "tapti-adrak-001-0", order: 0 }],
    tags: ["ginger", "adrak", "powder", "organic", "health", "digestion"],
    averageRating: 4.7,
    totalReviews: 0,
  },
  {
    name: "Premium Saffron Tea Blend",
    slug: "premium-saffron-tea-blend",
    description: "Premium Saffron Tea Blend - Exquisite blend of hand-picked black tea leaves infused with pure saffron threads. Rich, aromatic flavor with floral notes. Known for mood-enhancing and antioxidant properties. Luxury tea experience in every cup.",
    shortDescription: "Premium Saffron Tea, Exquisite Aroma & Rich Flavor",
    price: 450,
    originalPrice: 600,
    category: "Tea & Beverages",
    subcategory: "Premium Blends",
    sku: "TAPTI-SAFF-TEA-001",
    stock: 35,
    weight: 100,
    weightUnit: "g",
    isFeatured: true,
    isActive: true,
    images: [{ url: "/images/p23.jpg", publicId: "tapti-saff-tea-001-0", order: 0 }],
    tags: ["saffron", "tea", "premium", "kesar", "luxury", "antioxidant"],
    averageRating: 4.9,
    totalReviews: 0,
  },
  {
    name: "Jaggery Chai Saffron Tea",
    slug: "jaggery-chai-saffron-tea",
    description: "Jaggery Chai Saffron Tea - Traditional chai blend with pure saffron threads and natural jaggery. Perfectly balanced sweetness and aromatic spices. Healthy alternative to sugar-laden tea. Rich in iron and antioxidants. Authentic Indian taste.",
    shortDescription: "Jaggery Chai Saffron Tea, Traditional & Healthy",
    price: 380,
    originalPrice: 500,
    category: "Tea & Beverages",
    subcategory: "Premium Blends",
    sku: "TAPTI-JAG-CHAI-001",
    stock: 40,
    weight: 100,
    weightUnit: "g",
    isFeatured: true,
    isActive: true,
    images: [{ url: "/images/p23.jpg", publicId: "tapti-jag-chai-001-0", order: 0 }],
    tags: ["chai", "jaggery", "saffron", "tea", "healthy", "traditional"],
    averageRating: 4.8,
    totalReviews: 0,
  },
  {
    name: "Premium Chai Patti (Tea Leaves)",
    slug: "premium-chai-patti",
    description: "Premium Chai Patti - Hand-picked tea leaves from finest tea gardens. Strong, full-bodied flavor perfect for making authentic Indian chai. Rich in antioxidants and natural caffeine. Freshly packed for maximum aroma and taste.",
    shortDescription: "Premium Chai Patti, Hand-Picked Tea Leaves",
    price: 180,
    originalPrice: 240,
    category: "Tea & Beverages",
    subcategory: "Tea Leaves",
    sku: "TAPTI-CHAI-001",
    stock: 80,
    weight: 250,
    weightUnit: "g",
    isFeatured: false,
    isActive: true,
    images: [{ url: "/images/p23.jpg", publicId: "tapti-chai-001-0", order: 0 }],
    tags: ["chai", "tea", "patti", "leaves", "traditional", "antioxidant"],
    averageRating: 4.6,
    totalReviews: 0,
  },
  {
    name: "Premium Cold Pressed Peanut Oil",
    slug: "premium-cold-pressed-peanut-oil",
    description: "Premium Cold Pressed Peanut Oil - 100% pure and natural groundnut oil extracted using traditional cold press method. Rich in Vitamin E and monounsaturated fats. Perfect for Indian cooking, frying, and salads. Heart-healthy choice with nutty flavor.",
    shortDescription: "Cold Pressed Peanut Oil, Rich in Vitamin E",
    price: 350,
    originalPrice: 450,
    category: "Cooking Oils & Ghee",
    subcategory: "Oils",
    sku: "TAPTI-PEANUT-OIL-001",
    stock: 40,
    weight: 1,
    weightUnit: "L",
    isFeatured: false,
    isActive: true,
    images: [{ url: "/images/p2.jpg", publicId: "tapti-peanut-oil-001-0", order: 0 }],
    tags: ["peanut oil", "groundnut oil", "cold pressed", "healthy", "cooking oil"],
    averageRating: 4.7,
    totalReviews: 0,
  },
  {
    name: "Premium Cold Pressed Sunflower Oil",
    slug: "premium-cold-pressed-sunflower-oil",
    description: "Premium Cold Pressed Sunflower Oil - 100% pure and natural with light taste. Rich in Vitamin E and omega-6 fatty acids. Suitable for all types of cooking. Cholesterol-free and heart-friendly. High smoke point perfect for frying.",
    shortDescription: "Cold Pressed Sunflower Oil, Light & Healthy",
    price: 320,
    originalPrice: 420,
    category: "Cooking Oils & Ghee",
    subcategory: "Oils",
    sku: "TAPTI-SUNFLOWER-OIL-001",
    stock: 45,
    weight: 1,
    weightUnit: "L",
    isFeatured: false,
    isActive: true,
    images: [{ url: "/images/p3.jpg", publicId: "tapti-sunflower-oil-001-0", order: 0 }],
    tags: ["sunflower oil", "cold pressed", "healthy", "cooking oil", "vitamin e"],
    averageRating: 4.6,
    totalReviews: 0,
  },
  {
    name: "Premium Shudh Desi Ghee",
    slug: "premium-shudh-desi-ghee",
    description: "Premium Shudh Desi Ghee - 100% pure and authentic ghee made from cow's milk using traditional bilona method. Rich in nutrients with aromatic flavor. Perfect for cooking, temples, and Ayurvedic use. Chemical-free and full of goodness.",
    shortDescription: "Premium Desi Ghee, Made from Cow's Milk",
    price: 650,
    originalPrice: 850,
    category: "Cooking Oils & Ghee",
    subcategory: "Ghee",
    sku: "TAPTI-GHEE-001",
    stock: 30,
    weight: 500,
    weightUnit: "g",
    isFeatured: true,
    isActive: true,
    images: [{ url: "/images/p19.jpg", publicId: "tapti-ghee-001-0", order: 0 }],
    tags: ["ghee", "desi ghee", "cow ghee", "pure", "traditional", "healthy"],
    averageRating: 4.9,
    totalReviews: 0,
  },
  {
    name: "Premium Cold Pressed Mustard Oil",
    slug: "premium-cold-pressed-mustard-oil",
    description: "Premium Cold Pressed Mustard Oil - 100% pure kachi ghani mustard oil. Farm-sourced with rich aroma and pungent flavor. Rich in Omega-3 fatty acids. Perfect for Indian cooking, pickles, and massages. Traditional and authentic.",
    shortDescription: "Cold Pressed Mustard Oil, Farm Sourced & Pure",
    price: 380,
    originalPrice: 480,
    category: "Cooking Oils & Ghee",
    subcategory: "Oils",
    sku: "TAPTI-MUSTARD-OIL-001",
    stock: 35,
    weight: 1,
    weightUnit: "L",
    isFeatured: true,
    isActive: true,
    images: [{ url: "/images/p4.jpg", publicId: "tapti-mustard-oil-001-0", order: 0 }],
    tags: ["mustard oil", "sarso oil", "cold pressed", "omega-3", "traditional", "pickle"],
    averageRating: 4.8,
    totalReviews: 0,
  },
];

async function seedProducts() {
  try {
    console.log('🚀 Starting product seeding...\n');

    const mongoUri = process.env.MONGODB_URI;
    if (!mongoUri) {
      throw new Error('MONGODB_URI environment variable is not set. Check .env.local');
    }

    await mongoose.connect(mongoUri);
    console.log('✅ Connected to MongoDB\n');

    let insertedCount = 0;
    let skippedCount = 0;
    let updatedCount = 0;

    for (const productData of productsData) {
      try {
        // Check if product already exists by slug
        const existing = await Product.findOne({ slug: productData.slug });

        if (existing) {
          // Update existing product with latest data
          await Product.updateOne({ slug: productData.slug }, { $set: productData });
          updatedCount++;
          console.log(`🔄 Updated: ${productData.name}`);
        } else {
          // Insert new product
          await Product.create({
            ...productData,
            specifications: [],
            variants: [],
            hasVariants: false,
            seo: {
              metaTitle: productData.name,
              metaDescription: productData.description,
              keywords: productData.tags,
              ogImage: productData.images[0]?.url,
            },
          });
          insertedCount++;
          console.log(`✅ Inserted: ${productData.name}`);
        }
      } catch (error: any) {
        console.error(`❌ Error with ${productData.name}:`, error.message);
      }
    }

    // Verify total count
    const totalInDB = await Product.countDocuments({ isActive: true });

    console.log('\n📊 Seed Summary:');
    console.log(`   ✅ Inserted: ${insertedCount}`);
    console.log(`   🔄 Updated: ${updatedCount}`);
    console.log(`   📦 Total active products in DB: ${totalInDB}\n`);
    console.log('✅ Seeding completed!');

  } catch (error: any) {
    console.error('❌ Seeding failed:', error.message);
    process.exit(1);
  } finally {
    await mongoose.disconnect();
    console.log('👋 Disconnected from MongoDB');
  }
}

seedProducts();
