import mongoose, { Schema, Document } from 'mongoose';

/**
 * Source collection for the Atlas Search synonym mapping.
 *
 * Documents are stored in exactly the shape Atlas Search expects for an
 * `equivalent` synonym mapping — a flat list of interchangeable terms:
 *
 *   { mappingType: 'equivalent', synonyms: ['paracetamol', 'acetaminophen', 'paracetmol'] }
 *
 * Regenerated by `scripts/build-search-synonyms.ts` from `SALT_ALIASES` in
 * `src/lib/pharma/composition.ts` plus a curated brand/typo list. The Atlas
 * Search index (`scripts/atlas-search-index.json`) references this collection.
 */
export type SynonymMappingType = 'equivalent' | 'explicit';

export interface ISaltSynonym extends Document {
  mappingType: SynonymMappingType;
  synonyms: string[];
  /** Optional stable key so the generator can upsert idempotently. */
  groupKey?: string;
  createdAt: Date;
  updatedAt: Date;
}

const SaltSynonymSchema = new Schema<ISaltSynonym>(
  {
    mappingType: {
      type: String,
      enum: ['equivalent', 'explicit'],
      default: 'equivalent',
      required: true,
    },
    synonyms: {
      type: [String],
      required: true,
      validate: [(v: string[]) => v.length >= 2, 'A synonym group needs at least two terms'],
    },
    groupKey: { type: String, index: true, unique: true, sparse: true },
  },
  { timestamps: true, collection: 'salt_synonyms' }
);

export default mongoose.models.SaltSynonym ||
  mongoose.model<ISaltSynonym>('SaltSynonym', SaltSynonymSchema);
